let v = function dobro(x){ // NO JAVASCRIPT CONSEGUIMOS JOGAR UMA FUNÇÃO DENTRO DE UMA VARIAVEL!
    return x*2 // ESSE "RETURN" VAI RETORNAR O DOBRO DE "X" QUE É O PARAMETRO QUE IREMOS DAR VALOR NA CHAMADA DE FUNÇAÕ NA VARIAVEL!
}

console.log(v(5)) // CHAMANDO A VARIAVEL CUJA A FUNÇAÕ ESTÁ DENTRO DELA E PASSSANDO O PARAREMETRO PARA CALCULAR O DOBRO DELE