function fatorial(n){
    let fat = 1 // CRIOU UMA VARIAVEL FAT RECEBENDO 1
    for(let c = n; c > 1; c--){ // PARA C(CONTAGEM) VAI RECEBER O PARAMETRO ENQUANTO O PARAMETRO FOR MENOR QUE 1 JÁ QUE FATORIAL É UM NUMERO VEZES O SEU ANTECESSOR, O INCREMENTO VAI SER C-- POIS O PARAMETRO IRA PERDER UM NUMERO A CADA LOOP
        fat *= c // PARA FAT VAI FAZER VEZES O PARAMETRO E ESSE NUMERO IRA DIMINUIR ATÉ CHEGAR EM 1
    }
    return fat
}

console.log(fatorial(5))